services:
  db:
    image: postgres:16
    container_name: pgdb
    environment:
      POSTGRES_USER: taruun
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tasks
    ports:
      - "5434:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: taskscheduler
    depends_on:
      - db
    environment:
      DB_HOST: db     
      DB_PORT: 5432   
      DB_USER: taruun
      DB_PASS: 123456
      DB_NAME: tasks
    ports:
      - "3001:3000"

volumes:
  pgdata:
